
<div class="no-display" id="optionextended_link_file-template">
  <div id="{{id}}" class="file-row file-row-narrow">
     <span class="file-info">
        <span class="file-info-name">{{name}}</span>
        <span class="file-info-size">({{size}})</span>
     </span>
     <span class="progress-text"></span>
     <div class="clear"></div>
  </div>
</div>
<div class="no-display" id="optionextended_link_file-template-progress">
  {{percent}}% {{uploaded}} / {{total}}
</div>
<div class="files" style="width:100%;">       
   <div id="uploader_row" style="display:none"  class="hide_uploader_row" >            
      <div class="row" >
         <input type="hidden" id="optionextended_link_file_save" name="image" value="<?php echo $this->htmlEscape($this->getImageJson()) ?>" /> 
         <div id="optionextended_link_file" class="uploader" style="width:241px">
            <div id="optionextended_link_file-old" class="file-row-info">
              <img src="<?php echo $this->getSkinUrl('images/spacer.gif')?>" id="optionextended_link_file_img" width="100" style="display:none;" alt="" />                                      
            </div>
            <div id="optionextended_link_file-new" class="file-row-info new-file"></div>
            <div class="buttons">
               <div id="optionextended_link_file-install-flash" style="display:none">
                  <?php echo Mage::helper('media')->__('This content requires last version of Adobe Flash Player. <a href="%s">Get Flash</a>', 'http://www.adobe.com/go/getflash/') ?>
               </div>
            </div>
         </div>
         <img src="<?php echo $this->getSkinUrl('pektsekye/optionextended/delete_image.gif')?>" id="optionextended_link_file_delete" alt="<?php echo Mage::helper('catalog')->__('Delete') ?>" onclick="optionExtended.deleteImage()" class="optionextended-delete-image"  style="display:none"/>                                   
         <div id="optionextended_link_file_save_advice"></div>                                                
      </div>
   </div>
</div> 
<script type="text/javascript">
//<![CDATA[
var maxUploadFileSizeInBytes  = <?php echo $this->getDataMaxSizeInBytes() ?>;
var maxUploadFileSize = '<?php echo $this->getDataMaxSize() ?>';
optionExtended.uploaderUrl    = '<?php echo Mage::getBlockSingleton('adminhtml/media_uploader')->getUploaderUrl('media/uploaderSingle.swf'); ?>';
optionExtended.uploaderConfig = <?php echo $this->getConfigJson() ?>;
optionExtended.loadUploader();

//]]> 
</script>
