<select id="detailed_select"  onblur="optionExtended.showInput('detailed');" style="display:none;width:241px" multiple >
<option value=""></option>
<?php foreach($this->getOptions() as $optionId => $option): ?>
  <?php if(isset($option['values'])): ?>
    <optgroup label="<?php echo $this->htmlEscape($option['title']) ?>">  
    <?php foreach($option['values'] as $valueId => $value): ?>
      <option value="<?php echo $value['row_id'] ?>"><?php echo $this->htmlEscape($value['title']) ?> <?php echo $value['row_id'] ?></option>      
    <?php endforeach; ?>
    </optgroup> 
  <?php else: ?>
    <option value="<?php echo $option['row_id'] ?>"><?php echo $this->htmlEscape($option['title']) ?> <?php echo $option['row_id'] ?></option>             
  <?php endif; ?>    
<?php endforeach; ?>
</select>   
<select onchange="optionExtended.onChildrenShortSelectChange()" onblur="optionExtended.showInput('short');" id="short_select" style="display:none;width:241px" multiple >
<option value=""></option>
<?php foreach($this->getOptions() as $optionId => $option): ?>
  <option value="<?php echo $optionId ?>"><?php echo $this->htmlEscape($option['title']) ?> <?php echo isset($option['row_id']) ? $option['row_id'] : ''; ?></option>                
<?php endforeach; ?>
</select>&nbsp;
<span id="show_link" class="optionextended-children-showhide-link"><span onclick="optionExtended.showSelect('detailed');" title="<?php echo $this->__('Click to select certain values') ?>">S</span>&nbsp;<span onclick="optionExtended.showSelect('short');" title="<?php echo  $this->__('Click to select entire option with all its values')  ?>">s</span></span>
         
<script type="text/javascript">
//<![CDATA[

optionExtended.hasOptions = <?php echo count($this->getOptions()) > 0 ? 'true' : 'false'; ?>;
optionExtended.rowIdIsset = <?php echo $this->getRowIdIsset() ?>;
optionExtended.rowIdsByOption = <?php echo $this->getRowIdsByOption() ?>;

//]]> 
</script>
